<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$rules = [
    'array_syntax'                                  => ['syntax' => 'short'],
    'binary_operator_spaces'                        => [
        'operators' => [
            '='  => 'align_single_space',
            '=>' => 'align_single_space',
        ],
    ],
    'blank_line_after_namespace'                    => true,
    'blank_line_after_opening_tag'                  => true,
    'cast_spaces'                                   => ['space' => 'single'],
    'concat_space'                                  => ['spacing' => 'one'],
    'elseif'                                        => true,
    'encoding'                                      => true,
    'full_opening_tag'                              => true,
    'function_typehint_space'                       => true,
    'heredoc_to_nowdoc'                             => true,
    'include'                                       => true,
    'indentation_type'                              => true,
    'line_ending'                                   => true,
    'lowercase_cast'                                => true,
    'lowercase_keywords'                            => true,
    'native_function_casing'                        => true,
    'new_with_braces'                               => true,
    'normalize_index_brace'                         => true,
    'not_operator_with_space'                       => true,
    'no_blank_lines_after_class_opening'            => true,
    'no_blank_lines_after_phpdoc'                   => true,
    'no_closing_tag'                                => true,
    'no_empty_phpdoc'                               => true,
    'no_empty_statement'                            => true,
    'no_leading_import_slash'                       => true,
    'no_leading_namespace_whitespace'               => true,
    'no_mixed_echo_print'                           => ['use' => 'echo'],
    'no_multiline_whitespace_around_double_arrow'   => true,
    'no_short_bool_cast'                            => true,
    'no_singleline_whitespace_before_semicolons'    => true,
    'no_spaces_after_function_name'                 => true,
    'no_spaces_inside_parenthesis'                  => true,
    'no_trailing_comma_in_list_call'                => true,
    'no_trailing_comma_in_singleline_array'         => true,
    'no_trailing_whitespace'                        => true,
    'no_trailing_whitespace_in_comment'             => true,
    'no_unneeded_control_parentheses'               => true,
    'no_unreachable_default_argument_value'         => true,
    'no_unused_imports'                             => true,
    'no_useless_return'                             => true,
    'no_whitespace_before_comma_in_array'           => true,
    'no_whitespace_in_blank_line'                   => true,
    'object_operator_without_whitespace'            => true,
    'phpdoc_indent'                                 => true,
    'phpdoc_no_access'                              => true,
    'phpdoc_no_package'                             => true,
    'phpdoc_order'                                  => true,
    'phpdoc_scalar'                                 => true,
    'phpdoc_separation'                             => true,
    'phpdoc_single_line_var_spacing'                => true,
    'phpdoc_summary'                                => true,
    'phpdoc_trim'                                   => true,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_var_without_name'                       => true,
    'self_accessor'                                 => true,
    'short_scalar_cast'                             => true,
    'simplified_null_return'                        => true,
    'single_blank_line_at_eof'                      => true,
    'single_blank_line_before_namespace'            => true,
    'single_class_element_per_statement'            => true,
    'single_import_per_statement'                   => true,
    'single_line_after_imports'                     => true,
    'single_line_comment_style'                     => ['comment_types' => ['hash']],
    'space_after_semicolon'                         => ['remove_in_empty_for_expressions' => true],
    'standardize_not_equals'                        => true,
    'switch_case_semicolon_to_colon'                => true,
    'switch_case_space'                             => true,
    'ternary_operator_spaces'                       => true,
    'trim_array_spaces'                             => true,
    'unary_operator_spaces'                         => true,
    'whitespace_after_comma_in_array'               => true,
];

$finder = new Finder();
$config = new Config();

$finder->exclude([
                     'node_modules',
                     'vendor',
                 ])->in(__DIR__);

return $config->setRules($rules)->setFinder($finder)->setUsingCache(true)->setRiskyAllowed(true);
