preset: recommended

enabled:
  - align_equals
  - concat_with_spaces
  - not_operator_with_space

disabled:
  - concat_without_spaces
  - unalign_equals
  - trailing_comma_in_multiline_array

finder:
  path:
    - "src"
    - "tests"
