preset: recommended

finder:
  path:
    - "src"
    - "tests"

enabled:
  - align_equals
  - concat_with_spaces
  - not_operator_with_space

disabled:
  - unalign_equals
  - concat_without_spaces
  - phpdoc_separation
